spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  datasource:
    url: jdbc:postgresql://localhost:5433/rainbow_database
    username: unicorn_user
    password: magical_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml

server:
  port: 8080

messaging:
  id: PlayerOne
  currentConnection:
    queue: servicea
    exchange: game
    routingkey: servicea
  targetConnection:
    exchange: game
    routingKey: serviceb
