spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  cloud:
    stream:
      bindings:
        test:
          destination: test

server:
  port: 8080

messaging:
  current:
    queue: servicea
    exchange: game
    routingkey: servicea
  target:
    exchange: game
    routingKey: serviceb
